deepthought:
  version: 1.0.0
server:
  servlet:
    context-path: /dio-au
spring:
   security:
      oauth2:
         resourceserver:
            jwt:
               jwk-set-uri: https://id.dev.lab.dataright.io/auth/realms/deepthought/protocol/openid-connect/certs
